// AUTO-GENERATED by scripts/extractCaseStudies.mjs
// Do not edit manually — drop PDFs in /casestudy and re-run the script.

export interface DiscussionQuestion {
  question: string;
  hint?: string;
  modelAnswer: string;
}

export interface CaseStudy {
  id: string;
  title: string;
  source: string;
  category: string;
  difficulty: "foundational" | "intermediate" | "advanced";
  scenario: string;
  facts: string[];
  discussionQuestions: DiscussionQuestion[];
  analysis: {
    keyIssues: string[];
    whyItMatters: string;
    howToApproach: string[];
    commonMistakes: string[];
    conceptConnections: string[];
  };
}

export const caseStudies: CaseStudy[] = [];
